version: '3.8'

services:
  web:
    build: .
    container_name: secure-file-share-app
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver"
    volumes:
      - .:/secure-file-share
    ports:
      - "8000:8000"
    environment:
      - DEBUG=true
    