# Dockerfile
FROM python:3.9-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set work directory
WORKDIR /secure-file-share

# Install dependencies
COPY requirements.txt /secure-file-share/
RUN pip install -r requirements.txt

# Copy project
COPY . /secure-file-share/